
DECLARE
    v_count  INT;
    v_name VARCHAR2(20);
    TYPE namesarray IS VARRAY(15) OF VARCHAR2(20);
    names    namesarray;
BEGIN
    names := namesarray('faculties', 'courses', 'teachers', 'teachers_courses', 'students', 'students_courses', 'grades', 'groups', 'groups_students');

    FOR i IN 1..names.count LOOP
        v_name := names(i);
        
        SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = upper(v_name);
        IF v_count = 1 THEN
            DBMS_OUTPUT.PUT_LINE('Dropping table: ' || v_name);
            EXECUTE IMMEDIATE 'DROP TABLE '|| v_name || ' CASCADE CONSTRAINTS';
        END IF;
    END LOOP;
END;

/

CREATE TABLE faculties
(
  faculty_id Integer GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT faculties_PK PRIMARY KEY,
  name NVARCHAR2 (50) NOT NULL
);
  
CREATE TABLE courses
(
  course_id Integer GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT courses_PK PRIMARY KEY,
  name VARCHAR2 (50) NOT NULL
 );

CREATE TABLE teachers (
  teacher_id Integer GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT teacher_PK PRIMARY KEY,
  name VARCHAR2 (50) NOT NULL,
  surname VARCHAR2 (50) NOT NULL,
  date_employed DATE,
  faculties_faculty_id Integer CONSTRAINT teachers_faculty_FK REFERENCES faculties (faculty_id)
);
  
CREATE TABLE teachers_courses
(
  teacher_course_id Integer GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT teachers_courses_PK PRIMARY KEY,
  courses_course_id Integer CONSTRAINT teachers_courses_courses_FK REFERENCES courses (course_id),
  teachers_teacher_id Integer CONSTRAINT teachers_courses_teachers_FK REFERENCES teachers (teacher_id)
 );
  
  
CREATE TABLE students
(
  student_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT students_PK PRIMARY KEY  ,
  name NVARCHAR2 (50) NOT NULL ,
  surname NVARCHAR2 (50) NOT NULL ,
  birth_date DATE,
  semester INTEGER NOT NULL,
  faculties_facultie_id Integer CONSTRAINT students_faculties_FK REFERENCES faculties (faculty_id)
);
  
CREATE TABLE students_courses
(
  student_course_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT students_courses_PK PRIMARY KEY  ,
  courses_course_id Integer CONSTRAINT students_courses_courses_FK REFERENCES courses (course_id),
  students_student_id Integer CONSTRAINT students_courses_students_FK REFERENCES students (student_id)
  
);

CREATE TABLE grades
(
  grade_id NUMBER CONSTRAINT grades_PK PRIMARY KEY,
  grade INTEGER NOT NULL,
  courses_course_id Integer CONSTRAINT grades_courses_FK REFERENCES courses (course_id),
  students_student_id Integer CONSTRAINT grades_students_FK REFERENCES students (student_id)
);
  
CREATE TABLE groups
(
  group_id NVARCHAR2 (50) CONSTRAINT groups_PK PRIMARY KEY,
  courses_course_id Integer CONSTRAINT groups_courses_FK REFERENCES courses (course_id)
);
  
CREATE TABLE groups_students
(
  group_student_id INTEGER CONSTRAINT  groups_students_PK PRIMARY KEY,
  groups_group_id NVARCHAR2 (50) CONSTRAINT groups_students_groups_FK REFERENCES groups (group_id),
  students_student_id Integer CONSTRAINT groups_students_students_FK REFERENCES students (student_id)
);



