DROP TABLE groups_students; 
DROP TABLE groups;
DROP TABLE grades;
DROP TABLE students_courses;
DROP TABLE students;
DROP TABLE teachers_courses;
DROP TABLE teachers;
DROP TABLE courses;
DROP TABLE faculties;